### ISSUE TITLE
Assertion `m->pc <= M68K_ADDRESS_WIDTH' failed.

### ISSUE THREAD

**Issue by ghost** [merwaaan/genesis.js#3]
Hi

When trying to play The Addams Family, Air Diver, Aladdin, Alien 3 and some other games, I get this message :

megado-bin: megado/m68k/m68k.c:153: uint8_t m68k_step(M68k *): Assertion `m->pc <= M68K_ADDRESS_WIDTH' failed.

**Comment by fmdkdd** [comment]
Well, the emulator is still in a rough state for now.  But I can't seem to reproduce here on Aladdin (E) (md5: 9fbca26577b356e31c93ec55422697aa), which plays fine here.  Addams Family (UE) (md5: eba5f964addea18b70336d292a08698d) is just a black a screen, but doesn't crash.

**Comment by fmdkdd** [comment]
Can you give us more info on what ROM you ran and how you built the emulator?  Your operating system, compiler, etc?

**Comment by ghost** [comment]
I have followed the steps to build megado on linux (Ubuntu 17.04) and I use the same roms as you.

But I think I understand the problem: I thought archives work with megado. But in fact this is not the case. I tried Aladdin (E) [!].bin and it works.

**Comment by fmdkdd** [comment]
Ah indeed, archives are not supported.  As I said, "rough state" ;).  Thanks for looking into it!

**Comment by ghost** [comment]
I like to test new emulators.
